// ============================================================
//  RECIPE DATA — 23 recipes
//  To add more: copy any object below, give it a unique id,
//  and append it to the array. Ingredient names must be
//  lowercase and consistent for the matcher to work.
// ============================================================

const RECIPES = [

  // ══════════════════════════════════════
  //  BREAKFAST
  // ══════════════════════════════════════

  {
    id: "overnight-oats",
    name: "Overnight Oats",
    emoji: "🥣",
    mealTypes: ["breakfast"],
    tags: ["no-cook", "meal-prep", "healthy", "vegetarian"],
    time: "5 min + chill",
    calories: 300,
    servings: 1,
    rating: 4.7,
    description:
      "A zero-effort make-ahead breakfast. Oats and yogurt soak overnight into a thick, creamy bowl you can top with anything — fruit, nuts, honey, you name it.",
    ingredients: [
      { name: "rolled oats",  amount: "½ cup" },
      { name: "milk",         amount: "½ cup" },
      { name: "greek yogurt", amount: "¼ cup" },
      { name: "maple syrup",  amount: "1–1½ tbsp" },
      { name: "chia seeds",   amount: "½ tbsp (optional)" },
      { name: "cinnamon",     amount: "⅛ tsp" },
      { name: "salt",         amount: "pinch" },
    ],
    instructions: [
      "Combine oats, chia seeds (if using), maple syrup, cinnamon, and salt in a jar or lidded container.",
      "Add Greek yogurt and milk. Stir until fully combined — no dry clumps.",
      "Seal and refrigerate at least 4 hours or overnight.",
      "Stir before eating. Top with berries, sliced banana, a drizzle of honey, or nut butter.",
    ],
  },

  {
    id: "avocado-toast-egg",
    name: "Avocado Toast with Egg",
    emoji: "🥑",
    mealTypes: ["breakfast", "lunch"],
    tags: ["quick", "healthy", "vegetarian", "eggs"],
    time: "10 min",
    calories: 290,
    servings: 1,
    rating: 4.8,
    description:
      "Creamy smashed avocado on golden toast topped with a perfectly runny egg. Ready in ten minutes and endlessly riffable with toppings.",
    ingredients: [
      { name: "sourdough bread",   amount: "1 thick slice" },
      { name: "avocado",           amount: "1 ripe" },
      { name: "egg",               amount: "1–2 large" },
      { name: "lemon",             amount: "squeeze" },
      { name: "unsalted butter",   amount: "1 tsp" },
      { name: "salt",              amount: "to taste" },
      { name: "black pepper",      amount: "to taste" },
      { name: "red pepper flakes", amount: "pinch (optional)" },
    ],
    instructions: [
      "Toast the bread until golden and sturdy.",
      "Halve and pit the avocado. Scoop into a bowl, add lemon juice, salt, and pepper. Mash to your liking.",
      "Spread avocado generously over the toast.",
      "Melt butter in a non-stick pan over medium-low heat. Crack in egg and cook until whites set but yolk is still runny, about 3–4 minutes.",
      "Slide egg onto toast. Finish with flaky salt, cracked pepper, and red pepper flakes. Serve immediately.",
    ],
  },

  {
    id: "shakshuka",
    name: "Shakshuka",
    emoji: "🍳",
    mealTypes: ["breakfast", "lunch"],
    tags: ["mediterranean", "vegetarian", "eggs", "spiced"],
    time: "30 min",
    calories: 250,
    servings: 3,
    rating: 4.9,
    description:
      "Eggs poached directly in a rich, spiced tomato-and-pepper sauce. A Middle Eastern breakfast icon equally at home for brunch or a lazy weeknight dinner.",
    ingredients: [
      { name: "egg",                    amount: "5 large" },
      { name: "canned crushed tomatoes", amount: "1 can (28 oz)" },
      { name: "red bell pepper",        amount: "1, diced" },
      { name: "onion",                  amount: "1 medium, diced" },
      { name: "garlic",                 amount: "4 cloves, minced" },
      { name: "olive oil",              amount: "2 tbsp" },
      { name: "ground cumin",           amount: "1 tsp" },
      { name: "smoked paprika",         amount: "1 tsp" },
      { name: "chili powder",           amount: "½ tsp" },
      { name: "salt",                   amount: "to taste" },
      { name: "black pepper",           amount: "to taste" },
      { name: "fresh parsley",          amount: "handful, chopped" },
      { name: "feta cheese",            amount: "2 oz, crumbled (optional)" },
    ],
    instructions: [
      "Heat olive oil in a large, deep skillet over medium heat. Add onion and bell pepper. Cook 6–8 minutes until softened.",
      "Add garlic, cumin, smoked paprika, and chili powder. Stir and cook 1 minute until fragrant.",
      "Pour in crushed tomatoes, season with salt and pepper, and simmer on medium-low for 10 minutes until thickened.",
      "Create 5 wells in the sauce with the back of a spoon. Crack an egg into each well.",
      "Cover and cook on low 5–8 minutes until whites are set and yolks are still runny.",
      "Top with crumbled feta and fresh parsley. Serve straight from the pan with crusty bread or pita.",
    ],
  },

  {
    id: "buttermilk-pancakes",
    name: "Fluffy Buttermilk Pancakes",
    emoji: "🥞",
    mealTypes: ["breakfast"],
    tags: ["american", "vegetarian", "fluffy", "classic"],
    time: "25 min",
    calories: 340,
    servings: 4,
    rating: 4.8,
    description:
      "Golden, cloud-light pancakes with crisp edges and an airy interior. The buttermilk-and-baking-soda combination gives them lift you simply can't get any other way.",
    ingredients: [
      { name: "all-purpose flour",  amount: "2 cups" },
      { name: "buttermilk",        amount: "2 cups" },
      { name: "egg",               amount: "2 large" },
      { name: "unsalted butter",   amount: "3 tbsp, melted + more for pan" },
      { name: "sugar",             amount: "2 tbsp" },
      { name: "baking powder",     amount: "2 tsp" },
      { name: "baking soda",       amount: "½ tsp" },
      { name: "salt",              amount: "½ tsp" },
      { name: "vanilla extract",   amount: "1 tsp" },
      { name: "maple syrup",       amount: "to serve" },
    ],
    instructions: [
      "Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.",
      "In a separate bowl, whisk buttermilk, eggs, melted butter, and vanilla.",
      "Pour wet into dry. Fold until just combined — lumps are fine, do not over-mix.",
      "Rest batter 5 minutes. Heat a non-stick skillet over medium heat and lightly butter the surface.",
      "Pour ¼ cup batter per pancake. Cook until bubbles form and edges look set, 2–3 minutes. Flip and cook 1–2 minutes more until golden.",
      "Serve warm with maple syrup and extra butter.",
    ],
  },

  {
    id: "huevos-rancheros",
    name: "Huevos Rancheros",
    emoji: "🫔",
    mealTypes: ["breakfast", "lunch"],
    tags: ["mexican", "eggs", "hearty", "spicy"],
    time: "25 min",
    calories: 420,
    servings: 2,
    rating: 4.7,
    description:
      "Fried eggs over warm tortillas with smoky refried black beans and a quick tomato-chile sauce. Filling, bold, and impossible to eat without a smile.",
    ingredients: [
      { name: "egg",            amount: "4 large" },
      { name: "corn tortillas", amount: "4" },
      { name: "black beans",    amount: "1 can (15 oz), drained" },
      { name: "tomatoes",       amount: "2 large, diced (or 1 cup salsa)" },
      { name: "onion",          amount: "½, diced" },
      { name: "garlic",         amount: "2 cloves, minced" },
      { name: "jalapeño",       amount: "1, minced" },
      { name: "ground cumin",   amount: "½ tsp" },
      { name: "chili powder",   amount: "½ tsp" },
      { name: "olive oil",      amount: "2 tbsp" },
      { name: "avocado",        amount: "1, sliced" },
      { name: "fresh cilantro", amount: "for topping" },
      { name: "salt",           amount: "to taste" },
      { name: "black pepper",   amount: "to taste" },
    ],
    instructions: [
      "Make the ranchero sauce: heat 1 tbsp oil in a small pan. Sauté onion and jalapeño 3–4 min. Add garlic, cumin, and chili powder, cook 30 seconds. Add diced tomatoes, season with salt, and simmer 8–10 min until slightly thick.",
      "Warm black beans in a small pot with a splash of water. Mash roughly half with a fork. Season with salt.",
      "Warm tortillas in a dry skillet, 30 seconds per side.",
      "Fry eggs in remaining oil to your liking (sunny-side up is classic).",
      "Assemble: place 2 tortillas per plate, spread with black beans, top with 2 fried eggs, and spoon ranchero sauce over everything.",
      "Finish with avocado slices, fresh cilantro, and cracked pepper.",
    ],
  },

  // ══════════════════════════════════════
  //  LUNCH
  // ══════════════════════════════════════

  {
    id: "caprese-salad",
    name: "Classic Caprese Salad",
    emoji: "🍅",
    mealTypes: ["lunch"],
    tags: ["italian", "no-cook", "vegetarian", "salad"],
    time: "5 min",
    calories: 258,
    servings: 4,
    rating: 4.7,
    description:
      "The Italian summer classic — ripe tomatoes, fresh mozzarella, fragrant basil, good olive oil, and balsamic glaze. No cooking. Maximum flavour.",
    ingredients: [
      { name: "tomatoes",             amount: "3–4 large, sliced ¼ inch" },
      { name: "fresh mozzarella",     amount: "8 oz, sliced ¼ inch" },
      { name: "fresh basil",          amount: "1 large bunch" },
      { name: "extra virgin olive oil", amount: "2 tbsp" },
      { name: "balsamic glaze",       amount: "2 tbsp" },
      { name: "salt",                 amount: "flaky, to taste" },
      { name: "black pepper",         amount: "to taste" },
    ],
    instructions: [
      "Bring tomatoes to room temperature at least 30 minutes before serving — this makes a big flavour difference.",
      "Arrange alternating slices of tomato and mozzarella on a platter in an overlapping pattern.",
      "Tuck fresh basil leaves between the slices.",
      "Drizzle with extra virgin olive oil and balsamic glaze.",
      "Season with flaky sea salt and freshly cracked pepper. Serve immediately.",
    ],
  },

  {
    id: "greek-salad",
    name: "Classic Greek Salad",
    emoji: "🫙",
    mealTypes: ["lunch"],
    tags: ["mediterranean", "greek", "no-cook", "vegetarian"],
    time: "10 min",
    calories: 220,
    servings: 4,
    rating: 4.7,
    description:
      "The authentic Horiatiki — ripe tomatoes, cucumber, olives, red onion, and a slab of creamy feta dressed in nothing but good olive oil and oregano. Simple perfection.",
    ingredients: [
      { name: "tomatoes",              amount: "3 large, cut in wedges" },
      { name: "cucumber",              amount: "1 English, thickly sliced" },
      { name: "red onion",             amount: "½, thinly sliced" },
      { name: "kalamata olives",       amount: "½ cup" },
      { name: "feta cheese",           amount: "4 oz, in a slab or crumbled" },
      { name: "extra virgin olive oil", amount: "3–4 tbsp" },
      { name: "red wine vinegar",      amount: "1 tbsp (optional)" },
      { name: "dried oregano",         amount: "1 tsp" },
      { name: "salt",                  amount: "to taste" },
      { name: "black pepper",          amount: "to taste" },
    ],
    instructions: [
      "Combine tomato wedges, cucumber slices, and red onion in a large bowl or arrange on a platter.",
      "Scatter kalamata olives over the top.",
      "Place feta on top — traditionally in one slab, not pre-crumbled.",
      "Drizzle generously with extra virgin olive oil and a splash of red wine vinegar if using.",
      "Sprinkle with dried oregano, salt, and cracked pepper. Serve immediately.",
    ],
  },

  {
    id: "tomato-soup",
    name: "Creamy Tomato Soup",
    emoji: "🍲",
    mealTypes: ["lunch"],
    tags: ["vegetarian", "soup", "creamy", "comfort food"],
    time: "35 min",
    calories: 185,
    servings: 4,
    rating: 4.8,
    description:
      "Rich, velvety tomato soup with a touch of cream and fresh basil. Far better than anything from a can and almost as effortless.",
    ingredients: [
      { name: "canned crushed tomatoes", amount: "2 cans (28 oz each)" },
      { name: "onion",                  amount: "1 medium, diced" },
      { name: "garlic",                 amount: "4 cloves, minced" },
      { name: "unsalted butter",        amount: "2 tbsp" },
      { name: "olive oil",              amount: "1 tbsp" },
      { name: "chicken broth",          amount: "2 cups (or vegetable broth)" },
      { name: "heavy cream",            amount: "¼ cup" },
      { name: "fresh basil",            amount: "small bunch" },
      { name: "sugar",                  amount: "1 tsp" },
      { name: "salt",                   amount: "to taste" },
      { name: "black pepper",           amount: "to taste" },
    ],
    instructions: [
      "Melt butter with olive oil in a large pot over medium heat. Add onion and cook 5–7 minutes until soft.",
      "Add garlic and cook 1 minute more.",
      "Pour in crushed tomatoes and broth. Add sugar, salt, and pepper. Bring to a simmer.",
      "Simmer uncovered 20 minutes, stirring occasionally.",
      "Blend until completely smooth using an immersion blender (or in batches in a countertop blender).",
      "Stir in heavy cream and most of the basil. Taste and adjust seasoning.",
      "Serve hot with a swirl of cream, fresh basil, and cracked pepper. Outstanding with a grilled cheese.",
    ],
  },

  {
    id: "chicken-caesar-salad",
    name: "Chicken Caesar Salad",
    emoji: "🥗",
    mealTypes: ["lunch", "dinner"],
    tags: ["chicken", "salad", "classic", "american"],
    time: "25 min",
    calories: 380,
    servings: 4,
    rating: 4.8,
    description:
      "Crisp romaine, juicy pan-seared chicken, shaved parmesan, and crunchy croutons in a bold Caesar dressing. The salad everyone actually wants to eat.",
    ingredients: [
      { name: "chicken breast",     amount: "2 large (about 1½ lbs)" },
      { name: "romaine lettuce",    amount: "2 large heads, chopped" },
      { name: "parmesan cheese",    amount: "3 oz, shaved" },
      { name: "croutons",           amount: "2 cups" },
      { name: "lemon",              amount: "1, juiced" },
      { name: "garlic",             amount: "2 cloves, minced" },
      { name: "dijon mustard",      amount: "1 tsp" },
      { name: "worcestershire sauce", amount: "1 tsp" },
      { name: "olive oil",          amount: "3 tbsp + more for chicken" },
      { name: "salt",               amount: "to taste" },
      { name: "black pepper",       amount: "to taste" },
    ],
    instructions: [
      "Season chicken breasts with salt and pepper. Heat a skillet over medium-high with a drizzle of olive oil.",
      "Cook chicken 6–7 minutes per side until golden and cooked through (165°F). Rest 5 minutes, then slice.",
      "Make the dressing: whisk together lemon juice, garlic, Dijon, Worcestershire, and olive oil. Season generously with salt and pepper.",
      "Toss romaine with dressing in a large bowl until well coated.",
      "Add parmesan and croutons and toss gently.",
      "Divide among plates. Top with sliced chicken, extra parmesan, and cracked pepper.",
    ],
  },

  // ══════════════════════════════════════
  //  DINNER
  // ══════════════════════════════════════

  {
    id: "chicken-fricassee",
    name: "Chicken Fricassee",
    emoji: "🍗",
    mealTypes: ["dinner"],
    tags: ["french", "chicken", "creamy", "comfort food"],
    time: "1h 10m",
    calories: 610,
    servings: 6,
    rating: 5.0,
    description:
      "A classic French braised chicken dish with a rich, creamy white-wine sauce, tender carrots, and fragrant thyme. Pure comfort in a pot.",
    ingredients: [
      { name: "chicken thighs",    amount: "4" },
      { name: "chicken legs",      amount: "4" },
      { name: "olive oil",         amount: "1 tbsp" },
      { name: "unsalted butter",   amount: "1 tbsp" },
      { name: "onion",             amount: "1 small, diced" },
      { name: "garlic",            amount: "2 cloves, minced" },
      { name: "carrots",           amount: "2, sliced" },
      { name: "fresh thyme",       amount: "4 sprigs" },
      { name: "all-purpose flour", amount: "2 tbsp" },
      { name: "dry white wine",    amount: "½ cup" },
      { name: "chicken stock",     amount: "1½ cups" },
      { name: "heavy cream",       amount: "½ cup" },
      { name: "salt",              amount: "to taste" },
      { name: "black pepper",      amount: "to taste" },
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "Pat chicken dry and season generously with salt and pepper.",
      "Heat olive oil in a large oven-safe pot over medium-high. Brown chicken 4 minutes per side until golden. Remove and set aside.",
      "Reduce heat to low. Add butter, sauté diced onion and sliced carrots 7–10 minutes until softened.",
      "Add garlic and thyme, cook 30 seconds. Stir in flour and cook 1–2 minutes until nutty.",
      "Pour in white wine and simmer until slightly reduced, scraping up the browned bits.",
      "Add chicken stock, nestle chicken back in the pot, and bake uncovered at 350°F for 45 minutes.",
      "Stir in heavy cream, taste and adjust seasoning. Serve immediately.",
    ],
  },

  {
    id: "turkey-meatloaf",
    name: "Ground Turkey Meatloaf",
    emoji: "🍖",
    mealTypes: ["dinner"],
    tags: ["turkey", "baked", "american", "healthy"],
    time: "1h 5m",
    calories: 340,
    servings: 6,
    rating: 4.8,
    description:
      "A lighter spin on classic meatloaf packed with hidden vegetables and finished with a smoky chipotle-maple glaze. Juicy, flavourful, and crowd-pleasing.",
    ingredients: [
      { name: "ground turkey",        amount: "1½ lbs" },
      { name: "cremini mushrooms",    amount: "1 cup, finely chopped" },
      { name: "onion",                amount: "1 small, finely diced" },
      { name: "carrots",              amount: "1 small, grated" },
      { name: "red bell pepper",      amount: "½, finely diced" },
      { name: "garlic",               amount: "2 cloves, minced" },
      { name: "panko breadcrumbs",    amount: "¾ cup" },
      { name: "milk",                 amount: "¼ cup" },
      { name: "egg",                  amount: "1 large" },
      { name: "worcestershire sauce", amount: "2 tbsp" },
      { name: "dijon mustard",        amount: "1 tbsp" },
      { name: "tomato paste",         amount: "1 tbsp" },
      { name: "fresh parsley",        amount: "2 tbsp" },
      { name: "dried thyme",          amount: "½ tsp" },
      { name: "smoked paprika",       amount: "½ tsp" },
      { name: "salt",                 amount: "1 tsp" },
      { name: "black pepper",         amount: "½ tsp" },
      { name: "olive oil",            amount: "1 tbsp" },
      { name: "ketchup",              amount: "⅓ cup (glaze)" },
      { name: "maple syrup",          amount: "1 tbsp (glaze)" },
      { name: "balsamic vinegar",     amount: "1 tsp (glaze)" },
    ],
    instructions: [
      "Preheat oven to 375°F. Line a baking sheet with parchment paper.",
      "Heat olive oil in a skillet. Sauté mushrooms, onion, bell pepper, carrots, and garlic 5–7 minutes until soft. Let cool.",
      "Combine ground turkey with sautéed veggies, breadcrumbs, milk, egg, Worcestershire, mustard, tomato paste, herbs, and spices. Mix until just combined.",
      "Shape into a 9×4-inch loaf on the baking sheet. Bake uncovered 30 minutes.",
      "Whisk ketchup, maple syrup, and balsamic vinegar. Brush over loaf.",
      "Bake another 25–30 minutes until internal temp reaches 165°F. Rest 10 minutes before slicing.",
    ],
  },

  {
    id: "mexican-lime-chicken-soup",
    name: "Mexican Lime & Chicken Soup",
    emoji: "🍜",
    mealTypes: ["lunch", "dinner"],
    tags: ["mexican", "soup", "chicken", "citrus"],
    time: "45 min",
    calories: 280,
    servings: 4,
    rating: 4.9,
    description:
      "A bright, soul-warming caldo-style chicken soup with a punchy lime finish. Light yet deeply satisfying — perfect any time of year.",
    ingredients: [
      { name: "chicken thighs",  amount: "1–1½ lbs" },
      { name: "onion",           amount: "1 medium, diced" },
      { name: "garlic",          amount: "2–3 cloves, minced" },
      { name: "carrots",         amount: "2, sliced" },
      { name: "celery",          amount: "2 stalks, sliced" },
      { name: "roma tomatoes",   amount: "1–2, diced" },
      { name: "jalapeño",        amount: "1, sliced (optional)" },
      { name: "chicken broth",   amount: "6 cups" },
      { name: "bay leaf",        amount: "1" },
      { name: "oregano",         amount: "1 tsp" },
      { name: "lime",            amount: "2–3 (zest of 1, juice of 2–3)" },
      { name: "fresh cilantro",  amount: "a handful" },
      { name: "olive oil",       amount: "1 tbsp" },
      { name: "salt",            amount: "to taste" },
      { name: "black pepper",    amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large pot over medium-high. Sear chicken until lightly golden. Remove and set aside.",
      "Sauté onion, garlic, carrots, celery, and jalapeño 4–5 minutes.",
      "Add tomatoes and cook 2–3 minutes until they start to break down.",
      "Return chicken to pot. Add broth, bay leaf, oregano, salt, and pepper. Simmer 20–25 minutes.",
      "Remove chicken, shred, and return to pot. Remove bay leaf.",
      "Stir in lime zest and juice. Taste and adjust seasoning. Top with cilantro and serve.",
    ],
  },

  {
    id: "black-bean-tacos",
    name: "Vegetarian Black Bean Tacos",
    emoji: "🌮",
    mealTypes: ["lunch", "dinner"],
    tags: ["vegetarian", "mexican", "quick", "tacos"],
    time: "25 min",
    calories: 360,
    servings: 5,
    rating: 4.7,
    description:
      "Smoky, spiced black beans in warm tortillas with all your favourite toppings. A hearty meatless dinner under 30 minutes.",
    ingredients: [
      { name: "black beans",    amount: "2 cans (15 oz each), drained" },
      { name: "olive oil",      amount: "1 tbsp" },
      { name: "onion",          amount: "1 medium, diced" },
      { name: "garlic",         amount: "3 cloves, minced" },
      { name: "jalapeño",       amount: "1, seeded and minced" },
      { name: "chili powder",   amount: "1 tsp" },
      { name: "ground cumin",   amount: "1 tsp" },
      { name: "smoked paprika", amount: "½ tsp" },
      { name: "tomato paste",   amount: "1 tbsp" },
      { name: "lime",           amount: "1, juiced" },
      { name: "corn tortillas", amount: "10" },
      { name: "avocado",        amount: "2, sliced" },
      { name: "fresh cilantro", amount: "for topping" },
      { name: "salt",           amount: "to taste" },
      { name: "black pepper",   amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a skillet over medium heat. Cook onion 2–3 minutes until translucent.",
      "Add garlic and jalapeño and cook 30 seconds. Add beans, spices, and tomato paste. Stir to combine.",
      "Add a splash of water and cook 3–5 minutes until heated through. Mash half the beans to help the filling hold together. Season with salt, pepper, and lime juice.",
      "Warm tortillas in a dry skillet, 30 seconds per side.",
      "Fill with bean mixture. Top with avocado, cilantro, and any other toppings you like.",
    ],
  },

  {
    id: "baked-lemon-herb-salmon",
    name: "Baked Lemon Herb Salmon",
    emoji: "🐟",
    mealTypes: ["dinner"],
    tags: ["salmon", "healthy", "quick", "gluten-free"],
    time: "25 min",
    calories: 228,
    servings: 4,
    rating: 4.9,
    description:
      "Flaky salmon fillets coated in a garlic-lemon-herb butter, baked to perfection in under 20 minutes. Light, elegant, and virtually effortless.",
    ingredients: [
      { name: "salmon fillets",   amount: "4 (about 6 oz each)" },
      { name: "olive oil",        amount: "1 tbsp" },
      { name: "unsalted butter",  amount: "2 tbsp, melted" },
      { name: "garlic",           amount: "3 cloves, minced" },
      { name: "lemon",            amount: "1 (zest + juice of half)" },
      { name: "fresh parsley",    amount: "2 tbsp, chopped" },
      { name: "fresh dill",       amount: "1 tbsp, chopped" },
      { name: "salt",             amount: "½ tsp" },
      { name: "black pepper",     amount: "¼ tsp" },
    ],
    instructions: [
      "Preheat oven to 400°F. Line a baking sheet with foil or parchment and brush with olive oil.",
      "Combine melted butter, olive oil, garlic, lemon zest, lemon juice, parsley, dill, salt, and pepper.",
      "Pat salmon dry and place on the baking sheet. Spoon herb butter evenly over each fillet.",
      "Bake 15–18 minutes until opaque and flakes easily with a fork.",
      "Serve with roasted vegetables, rice, or a simple salad.",
    ],
  },

  {
    id: "spaghetti-carbonara",
    name: "Spaghetti Carbonara",
    emoji: "🍝",
    mealTypes: ["dinner"],
    tags: ["italian", "pasta", "classic", "quick"],
    time: "25 min",
    calories: 520,
    servings: 4,
    rating: 4.9,
    description:
      "The Roman classic done right — silky egg-and-parmesan sauce coating every strand of spaghetti with crispy pancetta and a punishing amount of black pepper. No cream. Never.",
    ingredients: [
      { name: "spaghetti",         amount: "400g" },
      { name: "pancetta",          amount: "150g, diced (or guanciale)" },
      { name: "egg",               amount: "4 large (2 whole + 2 yolks)" },
      { name: "parmesan cheese",   amount: "80g, finely grated" },
      { name: "pecorino romano",   amount: "40g, finely grated" },
      { name: "black pepper",      amount: "2 tsp, coarsely ground" },
      { name: "garlic",            amount: "1 clove (optional)" },
      { name: "salt",              amount: "for pasta water" },
    ],
    instructions: [
      "Cook spaghetti in heavily salted boiling water until al dente. Reserve 1 cup pasta water before draining.",
      "Fry pancetta in a large skillet over medium heat until crispy. Add garlic (whole) and remove it after 1 minute.",
      "Whisk eggs, yolks, parmesan, pecorino, and black pepper together in a bowl.",
      "Remove skillet from heat. Add hot pasta and toss with pancetta fat.",
      "Pour in egg mixture, tossing constantly and adding pasta water a splash at a time to create a glossy, silky sauce. Work fast — the heat cooks the eggs without scrambling.",
      "Serve immediately with extra parmesan and cracked pepper.",
    ],
  },

  {
    id: "ground-beef-tacos",
    name: "Seasoned Ground Beef Tacos",
    emoji: "🌮",
    mealTypes: ["dinner"],
    tags: ["mexican", "beef", "quick", "family-friendly"],
    time: "25 min",
    calories: 340,
    servings: 4,
    rating: 4.7,
    description:
      "Perfectly seasoned ground beef in warm tortillas with all your favourite toppings. A reliable weeknight staple that comes together in half an hour.",
    ingredients: [
      { name: "ground beef",    amount: "1½ lbs (80/20)" },
      { name: "corn tortillas", amount: "12" },
      { name: "onion",          amount: "1 medium, diced" },
      { name: "garlic",         amount: "3 cloves, minced" },
      { name: "chili powder",   amount: "2 tsp" },
      { name: "ground cumin",   amount: "1 tsp" },
      { name: "smoked paprika", amount: "½ tsp" },
      { name: "oregano",        amount: "½ tsp" },
      { name: "tomato paste",   amount: "2 tbsp" },
      { name: "lime",           amount: "1, juiced" },
      { name: "olive oil",      amount: "1 tbsp" },
      { name: "avocado",        amount: "2, sliced (topping)" },
      { name: "fresh cilantro", amount: "for topping" },
      { name: "salt",           amount: "to taste" },
      { name: "black pepper",   amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium-high. Add onion and cook 3–4 minutes until softened.",
      "Add ground beef, breaking up with a spoon. Brown 5–6 minutes. Drain excess fat.",
      "Add garlic, chili powder, cumin, smoked paprika, and oregano. Cook 1 minute.",
      "Stir in tomato paste and a splash of water. Cook 2 more minutes. Add lime juice, season with salt and pepper.",
      "Warm tortillas in a dry skillet, 30 seconds per side.",
      "Fill with beef, top with avocado, cilantro, salsa, and anything else you like.",
    ],
  },

  {
    id: "butter-chicken",
    name: "Butter Chicken",
    emoji: "🍛",
    mealTypes: ["dinner"],
    tags: ["indian", "chicken", "creamy", "curry"],
    time: "45 min",
    calories: 420,
    servings: 4,
    rating: 4.9,
    description:
      "The globally beloved Indian classic — tender chicken in a velvety, subtly spiced tomato-cream sauce with aromatic garam masala. Rich, warming, and deeply satisfying.",
    ingredients: [
      { name: "chicken breast",          amount: "1½ lbs, cut into 1-inch pieces" },
      { name: "canned crushed tomatoes", amount: "1 can (14 oz)" },
      { name: "onion",                   amount: "1 large, finely diced" },
      { name: "garlic",                  amount: "4 cloves, minced" },
      { name: "fresh ginger",            amount: "1 tbsp, grated" },
      { name: "unsalted butter",         amount: "3 tbsp" },
      { name: "heavy cream",             amount: "½ cup" },
      { name: "garam masala",            amount: "2 tsp" },
      { name: "ground cumin",            amount: "1 tsp" },
      { name: "chili powder",            amount: "1 tsp" },
      { name: "smoked paprika",          amount: "½ tsp" },
      { name: "turmeric",                amount: "¼ tsp" },
      { name: "olive oil",               amount: "2 tbsp" },
      { name: "fresh cilantro",          amount: "for topping" },
      { name: "salt",                    amount: "to taste" },
    ],
    instructions: [
      "Season chicken with salt, ½ tsp garam masala, and a pinch of turmeric. Heat olive oil in a large pan over medium-high and sear chicken 3–4 minutes per side until golden. Remove and set aside.",
      "Melt butter in the same pan. Add onion and cook 6–8 minutes until golden.",
      "Add garlic and ginger. Cook 1 minute. Add remaining spices, stir and cook 1 minute until very fragrant.",
      "Pour in crushed tomatoes. Simmer 10 minutes until the sauce deepens in colour.",
      "Blend sauce smooth with an immersion blender (optional but recommended).",
      "Return chicken to pan. Stir in heavy cream and simmer 8–10 minutes until cooked through and sauce is velvety.",
      "Taste and adjust seasoning. Serve over basmati rice with fresh cilantro and naan.",
    ],
  },

  {
    id: "shrimp-pasta",
    name: "Garlic Butter Shrimp Pasta",
    emoji: "🦐",
    mealTypes: ["dinner"],
    tags: ["shrimp", "pasta", "seafood", "quick"],
    time: "25 min",
    calories: 480,
    servings: 4,
    rating: 4.8,
    description:
      "Plump shrimp tossed with linguine in a rich garlic-butter sauce with lemon and white wine. An impressive dinner that comes together in 25 minutes.",
    ingredients: [
      { name: "shrimp",            amount: "1 lb, peeled and deveined" },
      { name: "linguine",          amount: "12 oz" },
      { name: "unsalted butter",   amount: "4 tbsp" },
      { name: "olive oil",         amount: "2 tbsp" },
      { name: "garlic",            amount: "6 cloves, minced" },
      { name: "dry white wine",    amount: "½ cup (or chicken broth)" },
      { name: "lemon",             amount: "1 (zest + juice)" },
      { name: "red pepper flakes", amount: "¼ tsp" },
      { name: "fresh parsley",     amount: "¼ cup, chopped" },
      { name: "parmesan cheese",   amount: "¼ cup, grated" },
      { name: "salt",              amount: "to taste" },
      { name: "black pepper",      amount: "to taste" },
    ],
    instructions: [
      "Cook linguine in heavily salted boiling water until al dente. Reserve ½ cup pasta water before draining.",
      "Pat shrimp dry, season with salt and pepper. Sear in 1 tbsp butter + 1 tbsp olive oil over medium-high, 1–2 minutes per side until pink. Remove and set aside.",
      "Add remaining butter and olive oil to the skillet. Cook garlic and red pepper flakes 1 minute.",
      "Pour in white wine and lemon juice. Simmer 2 minutes.",
      "Add pasta and toss, using pasta water to loosen into a silky sauce.",
      "Return shrimp. Add lemon zest and parsley. Toss and heat 1 minute. Serve with parmesan.",
    ],
  },

  {
    id: "beef-bolognese",
    name: "Beef Bolognese",
    emoji: "🫕",
    mealTypes: ["dinner"],
    tags: ["italian", "beef", "pasta", "slow-cooked"],
    time: "1h 30m",
    calories: 490,
    servings: 6,
    rating: 4.9,
    description:
      "The real Bolognese — a slow-cooked Italian meat ragù with ground beef, wine, and a splash of whole milk over thick spaghetti. Worth every minute on the stove.",
    ingredients: [
      { name: "ground beef",             amount: "1 lb" },
      { name: "spaghetti",               amount: "1 lb" },
      { name: "onion",                   amount: "1 large, finely diced" },
      { name: "carrots",                 amount: "1 large, finely diced" },
      { name: "celery",                  amount: "2 stalks, finely diced" },
      { name: "garlic",                  amount: "3 cloves, minced" },
      { name: "canned crushed tomatoes", amount: "1 can (28 oz)" },
      { name: "tomato paste",            amount: "2 tbsp" },
      { name: "dry red wine",            amount: "1 cup" },
      { name: "whole milk",              amount: "½ cup" },
      { name: "olive oil",               amount: "2 tbsp" },
      { name: "fresh parsley",           amount: "¼ cup, chopped" },
      { name: "parmesan cheese",         amount: "for serving" },
      { name: "salt",                    amount: "to taste" },
      { name: "black pepper",            amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large heavy pot over medium. Cook onion, carrot, and celery 8–10 minutes until very soft.",
      "Add garlic and cook 1 minute.",
      "Add ground beef and cook, breaking it up, until browned. Season with salt and pepper.",
      "Pour in red wine and cook until almost fully evaporated, about 5 minutes.",
      "Stir in tomato paste then crushed tomatoes. Reduce heat to low.",
      "Simmer uncovered for 1 hour, stirring occasionally. Add a splash of water if it dries out.",
      "Stir in whole milk in the last 5 minutes — this is the secret to a silky Bolognese.",
      "Toss with al dente pasta. Serve with parsley and a mountain of parmesan.",
    ],
  },

  {
    id: "pork-chops",
    name: "Pan-Seared Herb Pork Chops",
    emoji: "🥩",
    mealTypes: ["dinner"],
    tags: ["pork", "quick", "american", "pan-seared"],
    time: "20 min",
    calories: 320,
    servings: 4,
    rating: 4.7,
    description:
      "Bone-in pork chops with a golden, herb-crusted sear and a simple garlic-butter pan sauce. Ready in 20 minutes and impressive enough for guests.",
    ingredients: [
      { name: "pork chops",      amount: "4 bone-in, about 1 inch thick" },
      { name: "unsalted butter", amount: "2 tbsp" },
      { name: "olive oil",       amount: "1 tbsp" },
      { name: "garlic",          amount: "3 cloves, smashed" },
      { name: "fresh thyme",     amount: "4 sprigs" },
      { name: "fresh rosemary",  amount: "2 sprigs" },
      { name: "lemon",           amount: "½, juiced" },
      { name: "salt",            amount: "to taste" },
      { name: "black pepper",    amount: "to taste" },
    ],
    instructions: [
      "Remove pork chops from the fridge 20 minutes before cooking. Pat very dry and season generously on both sides.",
      "Heat olive oil in a heavy skillet (cast iron is ideal) over high heat until just smoking.",
      "Add pork chops and sear 3–4 minutes without moving until a deep golden crust forms. Flip.",
      "Reduce heat to medium. Add butter, garlic, thyme, and rosemary.",
      "Tilt the pan and baste the chops with the foaming butter continuously for 2–3 minutes until cooked through (145°F).",
      "Rest 5 minutes. Squeeze lemon into the pan juices and spoon over the chops.",
    ],
  },

  {
    id: "roasted-herb-chicken",
    name: "Roasted Herb Chicken Thighs",
    emoji: "🍗",
    mealTypes: ["dinner"],
    tags: ["chicken", "roasted", "easy", "weeknight"],
    time: "50 min",
    calories: 380,
    servings: 4,
    rating: 4.8,
    description:
      "Crispy-skinned, juicy chicken thighs roasted with garlic, lemon, and fresh herbs. One pan, minimal prep, maximum flavour — the definition of an easy weeknight dinner.",
    ingredients: [
      { name: "chicken thighs",  amount: "8 bone-in, skin-on" },
      { name: "garlic",          amount: "6 cloves, minced" },
      { name: "lemon",           amount: "1 (zest + juice)" },
      { name: "olive oil",       amount: "3 tbsp" },
      { name: "fresh rosemary",  amount: "3 sprigs, chopped" },
      { name: "fresh thyme",     amount: "4 sprigs" },
      { name: "smoked paprika",  amount: "1 tsp" },
      { name: "onion",           amount: "1 large, sliced" },
      { name: "salt",            amount: "1½ tsp" },
      { name: "black pepper",    amount: "½ tsp" },
    ],
    instructions: [
      "Preheat oven to 425°F. Mix garlic, lemon zest, lemon juice, olive oil, rosemary, smoked paprika, salt, and pepper into a paste.",
      "Pat chicken thighs dry. Coat all over with herb paste, getting some under the skin.",
      "Scatter sliced onion in a large baking dish. Arrange chicken skin-side up on top. Lay thyme sprigs around the pan.",
      "Roast 40–45 minutes until skin is deeply golden and crispy and internal temp reaches 165°F.",
      "Rest 5 minutes. Spoon pan juices over the top and serve.",
    ],
  },

  {
    id: "mushroom-risotto",
    name: "Mushroom Risotto",
    emoji: "🍄",
    mealTypes: ["dinner"],
    tags: ["vegetarian", "italian", "creamy", "comfort food"],
    time: "45 min",
    calories: 420,
    servings: 4,
    rating: 4.8,
    description:
      "Deeply savoury restaurant-quality risotto with wild mushrooms, white wine, and a generous finish of butter and parmesan. The kind of dish that makes people go quiet at the table.",
    ingredients: [
      { name: "arborio rice",    amount: "1½ cups" },
      { name: "cremini mushrooms", amount: "12 oz, sliced" },
      { name: "onion",           amount: "1 small, finely diced" },
      { name: "garlic",          amount: "3 cloves, minced" },
      { name: "dry white wine",  amount: "½ cup" },
      { name: "chicken broth",   amount: "5–6 cups, warmed (or vegetable broth)" },
      { name: "parmesan cheese", amount: "¾ cup, finely grated" },
      { name: "unsalted butter", amount: "3 tbsp" },
      { name: "olive oil",       amount: "2 tbsp" },
      { name: "fresh thyme",     amount: "3 sprigs" },
      { name: "fresh parsley",   amount: "¼ cup, chopped" },
      { name: "salt",            amount: "to taste" },
      { name: "black pepper",    amount: "to taste" },
    ],
    instructions: [
      "Keep broth warm in a separate pot over low heat throughout.",
      "Heat 1 tbsp butter and olive oil over medium-high. Add mushrooms in a single layer — don't stir — and cook 4–5 minutes until golden. Season and remove.",
      "Add remaining butter and olive oil. Sauté onion over medium 4–5 minutes. Add garlic and thyme, cook 1 minute.",
      "Add arborio rice. Toast, stirring, 2 minutes until edges turn translucent.",
      "Pour in white wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring frequently and waiting until each ladle is absorbed before adding the next. About 18–20 minutes total.",
      "Stir in mushrooms, parmesan, and a final tablespoon of cold butter. Texture should be fluid — 'all'onda' (like a wave).",
      "Taste, adjust salt, and serve immediately with parsley and extra parmesan.",
    ],
  },

  {
    id: "steak-fajitas",
    name: "Sheet Pan Steak Fajitas",
    emoji: "🌯",
    mealTypes: ["dinner"],
    tags: ["mexican", "beef", "quick", "sheet-pan"],
    time: "35 min",
    calories: 380,
    servings: 4,
    rating: 4.7,
    description:
      "Juicy sliced flank steak and charred peppers and onions roasted together on one sheet pan with a smoky fajita marinade. All the flavour, minimal cleanup.",
    ingredients: [
      { name: "flank steak",      amount: "1½ lbs" },
      { name: "red bell pepper",  amount: "2, sliced" },
      { name: "green bell pepper", amount: "1, sliced" },
      { name: "onion",            amount: "2 large, sliced" },
      { name: "garlic",           amount: "3 cloves, minced" },
      { name: "olive oil",        amount: "3 tbsp" },
      { name: "lime",             amount: "2 (juice + zest of 1)" },
      { name: "chili powder",     amount: "2 tsp" },
      { name: "ground cumin",     amount: "1 tsp" },
      { name: "smoked paprika",   amount: "1 tsp" },
      { name: "oregano",          amount: "½ tsp" },
      { name: "flour tortillas",  amount: "8 large" },
      { name: "avocado",          amount: "2, sliced" },
      { name: "fresh cilantro",   amount: "for serving" },
      { name: "salt",             amount: "to taste" },
      { name: "black pepper",     amount: "to taste" },
    ],
    instructions: [
      "Whisk olive oil, lime juice and zest, garlic, chili powder, cumin, smoked paprika, oregano, salt, and pepper into a marinade.",
      "Slice flank steak against the grain into thin strips. Toss with half the marinade. Marinate 15–30 minutes.",
      "Preheat oven to 425°F. Toss peppers and onion with remaining marinade and spread on a large sheet pan.",
      "Roast vegetables 15 minutes. Push to the edges, add steak strips to the centre.",
      "Roast another 10–12 minutes until steak is medium and vegetables are slightly charred.",
      "Rest 3 minutes. Warm tortillas in a dry skillet. Serve in tortillas with avocado and cilantro.",
    ],
  },

];
