// ============================================================
//  RECIPE DATA
//  To add a new recipe, copy one of the objects below and
//  append it to the RECIPES array. Keep ingredient names
//  lowercase and consistent so the matcher can find them.
// ============================================================

const RECIPES = [

  // ── BREAKFAST ──────────────────────────────────────────

  {
    id: "overnight-oats",
    name: "Overnight Oats",
    emoji: "🥣",
    mealTypes: ["breakfast"],
    tags: ["no-cook", "meal-prep", "healthy", "vegetarian"],
    time: "5 min + chill",
    calories: 300,
    servings: 1,
    rating: 4.7,
    description:
      "A zero-effort make-ahead breakfast. Oats and yogurt soak overnight for a creamy, satisfying bowl you can top with anything — fruit, nuts, honey, whatever you have.",
    ingredients: [
      { name: "rolled oats",   amount: "½ cup" },
      { name: "milk",          amount: "½ cup" },
      { name: "greek yogurt",  amount: "¼ cup" },
      { name: "maple syrup",   amount: "1–1½ tbsp" },
      { name: "chia seeds",    amount: "½ tbsp (optional)" },
      { name: "cinnamon",      amount: "⅛ tsp" },
      { name: "salt",          amount: "pinch" },
    ],
    instructions: [
      "Combine rolled oats, chia seeds (if using), maple syrup, cinnamon, and salt in a Mason jar or lidded container.",
      "Add Greek yogurt and milk. Stir thoroughly until no clumps remain.",
      "Seal and refrigerate for at least 4 hours, or overnight.",
      "Stir before serving. Top with fresh berries, sliced banana, a drizzle of honey, or your favourite nut butter.",
    ],
  },

  {
    id: "avocado-toast-egg",
    name: "Avocado Toast with Egg",
    emoji: "🥑",
    mealTypes: ["breakfast", "lunch"],
    tags: ["quick", "healthy", "vegetarian", "eggs"],
    time: "10 min",
    calories: 290,
    servings: 1,
    rating: 4.8,
    description:
      "Creamy smashed avocado on golden toast, crowned with a perfectly runny egg. Ready in ten minutes and endlessly riffable with whatever toppings you have.",
    ingredients: [
      { name: "sourdough bread",  amount: "1 thick slice" },
      { name: "avocado",          amount: "1 ripe" },
      { name: "egg",              amount: "1–2 large" },
      { name: "lemon",            amount: "squeeze" },
      { name: "unsalted butter",  amount: "1 tsp (for egg)" },
      { name: "salt",             amount: "to taste" },
      { name: "black pepper",     amount: "to taste" },
      { name: "red pepper flakes", amount: "pinch (optional)" },
    ],
    instructions: [
      "Toast the bread until golden and sturdy.",
      "Halve and pit the avocado. Scoop flesh into a bowl, add a squeeze of lemon, salt, and pepper. Mash to your preferred texture.",
      "Spread avocado generously over the toast.",
      "Melt butter in a non-stick pan over medium-low heat. Crack in the egg and cook until whites are set but yolk is still runny, about 3–4 minutes.",
      "Slide the egg onto the toast. Finish with flaky salt, cracked pepper, and a pinch of red pepper flakes. Serve immediately.",
    ],
  },

  // ── LUNCH ──────────────────────────────────────────────

  {
    id: "caprese-salad",
    name: "Classic Caprese Salad",
    emoji: "🍅",
    mealTypes: ["lunch"],
    tags: ["italian", "no-cook", "vegetarian", "salad"],
    time: "5 min",
    calories: 258,
    servings: 4,
    rating: 4.7,
    description:
      "The Italian summer classic — ripe tomatoes, fresh mozzarella, fragrant basil, a drizzle of good olive oil, and balsamic glaze. No cooking, maximum flavour.",
    ingredients: [
      { name: "tomatoes",             amount: "3–4 large, sliced ¼ inch" },
      { name: "fresh mozzarella",     amount: "8 oz, sliced ¼ inch" },
      { name: "fresh basil",          amount: "1 large bunch" },
      { name: "extra virgin olive oil", amount: "2 tbsp" },
      { name: "balsamic glaze",       amount: "2 tbsp" },
      { name: "salt",                 amount: "flaky, to taste" },
      { name: "black pepper",         amount: "to taste" },
    ],
    instructions: [
      "Bring tomatoes to room temperature at least 30 minutes before serving — this makes a huge difference in flavour.",
      "Arrange alternating slices of tomato and mozzarella on a platter in an overlapping pattern.",
      "Tuck fresh basil leaves between and over the slices.",
      "Drizzle with extra virgin olive oil, then balsamic glaze.",
      "Season with flaky sea salt and freshly cracked black pepper. Serve immediately.",
    ],
  },

  // ── DINNER ─────────────────────────────────────────────

  {
    id: "chicken-fricassee",
    name: "Chicken Fricassee",
    emoji: "🍗",
    mealTypes: ["dinner"],
    tags: ["french", "chicken", "creamy", "comfort food"],
    time: "1h 10m",
    calories: 610,
    servings: 6,
    rating: 5.0,
    description:
      "A classic French braised chicken dish with a rich, creamy white-wine sauce, tender carrots, and fragrant thyme. Pure comfort in a pot.",
    ingredients: [
      { name: "chicken thighs",    amount: "4" },
      { name: "chicken legs",      amount: "4" },
      { name: "olive oil",         amount: "1 tbsp" },
      { name: "unsalted butter",   amount: "1 tbsp" },
      { name: "onion",             amount: "1 small, diced" },
      { name: "garlic",            amount: "2 cloves, minced" },
      { name: "carrots",           amount: "2, sliced" },
      { name: "fresh thyme",       amount: "4 sprigs" },
      { name: "all-purpose flour", amount: "2 tbsp" },
      { name: "dry white wine",    amount: "½ cup" },
      { name: "chicken stock",     amount: "1½ cups" },
      { name: "heavy cream",       amount: "½ cup" },
      { name: "salt",              amount: "to taste" },
      { name: "black pepper",      amount: "to taste" },
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "Pat chicken dry and season generously with salt and pepper.",
      "Heat olive oil in a large oven-safe pot over medium-high heat. Brown chicken 4 minutes per side until golden. Remove and set aside.",
      "Reduce heat to low, add butter. Sauté diced onion and sliced carrots for 7–10 minutes until softened.",
      "Add minced garlic and thyme sprigs. Cook 30 seconds until fragrant.",
      "Stir in flour and cook 1–2 minutes until nutty-smelling.",
      "Pour in white wine and simmer until slightly reduced, scraping up the browned bits.",
      "Add chicken stock and nestle the chicken back in the pot.",
      "Bake uncovered at 350°F for 45 minutes.",
      "Remove from oven, stir in heavy cream. Taste and adjust seasoning. Serve immediately.",
    ],
  },

  {
    id: "turkey-meatloaf",
    name: "Ground Turkey Meatloaf",
    emoji: "🍖",
    mealTypes: ["dinner"],
    tags: ["turkey", "baked", "american", "healthy"],
    time: "1h 5m",
    calories: 340,
    servings: 6,
    rating: 4.8,
    description:
      "A lighter spin on classic meatloaf packed with hidden vegetables and finished with a smoky chipotle-maple glaze. Juicy, flavourful, and crowd-pleasing.",
    ingredients: [
      { name: "ground turkey",       amount: "1½ lbs" },
      { name: "cremini mushrooms",   amount: "1 cup, finely chopped" },
      { name: "onion",               amount: "1 small, finely diced" },
      { name: "carrots",             amount: "1 small, grated" },
      { name: "red bell pepper",     amount: "½, finely diced" },
      { name: "garlic",              amount: "2 cloves, minced" },
      { name: "panko breadcrumbs",   amount: "¾ cup" },
      { name: "milk",                amount: "¼ cup" },
      { name: "egg",                 amount: "1 large" },
      { name: "worcestershire sauce", amount: "2 tbsp" },
      { name: "dijon mustard",       amount: "1 tbsp" },
      { name: "tomato paste",        amount: "1 tbsp" },
      { name: "fresh parsley",       amount: "2 tbsp" },
      { name: "dried thyme",         amount: "½ tsp" },
      { name: "smoked paprika",      amount: "½ tsp" },
      { name: "salt",                amount: "1 tsp" },
      { name: "black pepper",        amount: "½ tsp" },
      { name: "olive oil",           amount: "1 tbsp" },
      { name: "ketchup",             amount: "⅓ cup (glaze)" },
      { name: "maple syrup",         amount: "1 tbsp (glaze)" },
      { name: "balsamic vinegar",    amount: "1 tsp (glaze)" },
    ],
    instructions: [
      "Preheat oven to 375°F. Line a baking sheet with parchment paper.",
      "Heat olive oil in a skillet over medium heat. Sauté mushrooms, onion, bell pepper, carrots, and garlic for 5–7 minutes until soft. Let cool slightly.",
      "In a large bowl, combine ground turkey with the sautéed vegetables, breadcrumbs, milk, egg, Worcestershire, mustard, tomato paste, herbs, and spices. Mix until just combined.",
      "Shape into a 9×4-inch loaf on the prepared baking sheet.",
      "Bake uncovered for 30 minutes.",
      "Whisk together ketchup, maple syrup, and balsamic vinegar for the glaze. Brush generously over the loaf.",
      "Continue baking 25–30 minutes until internal temperature reaches 165°F.",
      "Rest 10 minutes before slicing.",
    ],
  },

  {
    id: "mexican-lime-chicken-soup",
    name: "Mexican Lime & Chicken Soup",
    emoji: "🍜",
    mealTypes: ["lunch", "dinner"],
    tags: ["mexican", "soup", "chicken", "citrus"],
    time: "45 min",
    calories: 280,
    servings: 4,
    rating: 4.9,
    description:
      "A bright, soul-warming caldo-style chicken soup with a punchy lime finish. Light yet deeply satisfying — perfect any time of year.",
    ingredients: [
      { name: "chicken thighs",  amount: "1–1½ lbs" },
      { name: "onion",           amount: "1 medium, diced" },
      { name: "garlic",          amount: "2–3 cloves, minced" },
      { name: "carrots",         amount: "2, sliced" },
      { name: "celery",          amount: "2 stalks, sliced" },
      { name: "roma tomatoes",   amount: "1–2, diced" },
      { name: "jalapeño",        amount: "1, sliced (optional)" },
      { name: "chicken broth",   amount: "6 cups" },
      { name: "bay leaf",        amount: "1" },
      { name: "oregano",         amount: "1 tsp" },
      { name: "lime",            amount: "2–3 (zest of 1, juice of 2–3)" },
      { name: "fresh cilantro",  amount: "a handful" },
      { name: "olive oil",       amount: "1 tbsp" },
      { name: "salt",            amount: "to taste" },
      { name: "black pepper",    amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large pot over medium-high heat. Sear chicken until lightly golden on both sides. Remove and set aside.",
      "In the same pot, sauté onion, garlic, carrots, celery, and jalapeño for 4–5 minutes.",
      "Add tomatoes and cook 2–3 minutes until they begin to break down.",
      "Return chicken to the pot. Add broth, bay leaf, oregano, salt, and pepper.",
      "Bring to a boil, then simmer 20–25 minutes until chicken is fully cooked.",
      "Remove chicken, shred with two forks, and return to the pot.",
      "Remove bay leaf. Stir in lime zest and juice. Taste and adjust seasoning.",
      "Ladle into bowls, top with fresh cilantro. Serve with warm tortillas or avocado.",
    ],
  },

  {
    id: "black-bean-tacos",
    name: "Vegetarian Black Bean Tacos",
    emoji: "🌮",
    mealTypes: ["lunch", "dinner"],
    tags: ["vegetarian", "mexican", "quick", "tacos"],
    time: "25 min",
    calories: 360,
    servings: 5,
    rating: 4.7,
    description:
      "Smoky, spiced black beans in warm tortillas with all your favourite toppings. A hearty meatless weeknight dinner that's on the table in under 30 minutes.",
    ingredients: [
      { name: "black beans",     amount: "2 cans (15 oz each), drained" },
      { name: "olive oil",       amount: "1 tbsp" },
      { name: "onion",           amount: "1 medium, diced" },
      { name: "garlic",          amount: "3 cloves, minced" },
      { name: "jalapeño",        amount: "1, seeded and minced (optional)" },
      { name: "chili powder",    amount: "1 tsp" },
      { name: "ground cumin",    amount: "1 tsp" },
      { name: "smoked paprika",  amount: "½ tsp" },
      { name: "tomato paste",    amount: "1 tbsp" },
      { name: "lime",            amount: "1, juiced" },
      { name: "corn tortillas",  amount: "10" },
      { name: "avocado",         amount: "2, sliced (topping)" },
      { name: "fresh cilantro",  amount: "for topping" },
      { name: "salt",            amount: "to taste" },
      { name: "black pepper",    amount: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium heat. Add diced onion and cook 2–3 minutes until translucent.",
      "Add garlic and jalapeño (if using) and cook 30 seconds more.",
      "Add black beans, chili powder, cumin, smoked paprika, and tomato paste. Stir to combine.",
      "Add a splash of water or broth and cook 3–5 minutes until heated through and slightly reduced.",
      "Roughly mash half the beans in the pan — this helps the filling hold together. Season with salt, pepper, and lime juice.",
      "Warm tortillas in a dry skillet, 30 seconds per side.",
      "Fill each tortilla with bean mixture. Top with avocado, cilantro, and any other toppings you like.",
    ],
  },

  {
    id: "baked-lemon-herb-salmon",
    name: "Baked Lemon Herb Salmon",
    emoji: "🐟",
    mealTypes: ["dinner"],
    tags: ["salmon", "healthy", "quick", "gluten-free"],
    time: "25 min",
    calories: 228,
    servings: 4,
    rating: 4.9,
    description:
      "Flaky salmon fillets coated in a garlic-lemon-herb butter and baked to perfection in under 20 minutes. Light, elegant, and virtually effortless.",
    ingredients: [
      { name: "salmon fillets",   amount: "4 (about 6 oz each)" },
      { name: "olive oil",        amount: "1 tbsp" },
      { name: "unsalted butter",  amount: "2 tbsp, melted" },
      { name: "garlic",           amount: "3 cloves, minced" },
      { name: "lemon",            amount: "1 (zest + juice of half)" },
      { name: "fresh parsley",    amount: "2 tbsp, finely chopped" },
      { name: "fresh dill",       amount: "1 tbsp, finely chopped" },
      { name: "salt",             amount: "½ tsp" },
      { name: "black pepper",     amount: "¼ tsp" },
    ],
    instructions: [
      "Preheat oven to 400°F. Line a rimmed baking sheet with foil or parchment and brush with olive oil.",
      "In a small bowl, combine melted butter, olive oil, minced garlic, lemon zest, lemon juice, parsley, dill, salt, and pepper.",
      "Pat salmon fillets dry and place on the baking sheet. Spoon the herb butter evenly over each fillet.",
      "Bake 15–18 minutes (about 10 minutes per inch of thickness) until the salmon is opaque and flakes easily with a fork.",
      "Serve warm with roasted vegetables, rice, or a simple salad.",
    ],
  },

];
